// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhMbulLyAp5Wgwu9KK4zzW0Q62DJ55lQk',
    appId: '1:1089074875485:web:9e07d7ee88baa5c0be91b4',
    messagingSenderId: '1089074875485',
    projectId: 'flutter-app-back',
    authDomain: 'flutter-app-back.firebaseapp.com',
    databaseURL: 'https://flutter-app-back-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-back.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX12MzN4ClKgiQ6QyD-HHQ62YDA4R9juE',
    appId: '1:1089074875485:android:f22360c5bba1e981be91b4',
    messagingSenderId: '1089074875485',
    projectId: 'flutter-app-back',
    databaseURL: 'https://flutter-app-back-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-back.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdEA7wzHz8R0lUFfn0VvmF5PaH1vL9jUY',
    appId: '1:1089074875485:ios:bbe590a3478444f5be91b4',
    messagingSenderId: '1089074875485',
    projectId: 'flutter-app-back',
    databaseURL: 'https://flutter-app-back-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-back.appspot.com',
    iosClientId: '1089074875485-b9tkke712bicgod6iqcrlmu48mqljkfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfgApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdEA7wzHz8R0lUFfn0VvmF5PaH1vL9jUY',
    appId: '1:1089074875485:ios:bbe590a3478444f5be91b4',
    messagingSenderId: '1089074875485',
    projectId: 'flutter-app-back',
    databaseURL: 'https://flutter-app-back-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-back.appspot.com',
    iosClientId: '1089074875485-b9tkke712bicgod6iqcrlmu48mqljkfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfgApp',
  );
}
